FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM radmgrp/sdk:8.0 AS build
# RUN apt-get update -y && \
#     apt-get install -y clang zlib1g-dev

WORKDIR /app
COPY . .
RUN dotnet restore && \
    dotnet test --configuration Release --no-restore

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["./WeatherApi"]
